# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('year', models.PositiveSmallIntegerField()),
                ('rating', models.CharField(max_length=5)),
                ('released', models.DateField()),
                ('runtime', models.DurationField()),
                ('genre', models.TextField()),
                ('director', models.TextField()),
                ('writer', models.TextField()),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.TextField()),
                ('country', models.TextField()),
                ('awards', models.TextField()),
                ('poster', models.URLField()),
                ('ratings', models.TextField()),
                ('metascore', models.PositiveSmallIntegerField()),
                ('imdb_rating', models.FloatField()),
                ('imdb_votes', models.PositiveIntegerField()),
                ('imdb_id', models.CharField(max_length=12)),
                ('content_type', models.TextField()),
                ('dvd', models.DateField()),
                ('box_office', models.PositiveIntegerField()),
                ('production', models.TextField()),
                ('website', models.URLField()),
                ('response', models.BooleanField()),
            ],
        ),
    ]
