# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefinder', '0002_auto_20170418_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='released',
            field=models.DateField(blank=True, null=True),
        ),
    ]
