# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviefinder', '0004_auto_20170418_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='Title',
        ),
    ]
