# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviefinder', '0005_auto_20170418_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='actors',
            new_name='Actors',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='awards',
            new_name='Awards',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='box_office',
            new_name='BoxOffice',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='content_type',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='dvd',
            new_name='DVD',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='metascore',
            new_name='Metascore',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='poster',
            new_name='Poster',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='rating',
            new_name='Rated',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='released',
            new_name='Released',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='response',
            new_name='Response',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='runtime',
            new_name='Runtime',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='website',
            new_name='Website',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='writer',
            new_name='Writer',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='Year',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='imdb_id',
            new_name='imdbId',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='imdb_rating',
            new_name='imdbRating',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='imdb_votes',
            new_name='imdbVotes',
        ),
    ]
