# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefinder', '0006_auto_20170418_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='Director',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='language',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='plot',
            new_name='Plot',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='production',
            new_name='Production',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='ratings',
            new_name='Ratings',
        ),
        migrations.AlterField(
            model_name='movie',
            name='BoxOffice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='DVD',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Released',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Runtime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
