# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviefinder', '0008_auto_20170418_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Rated',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbId',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
